### ISSUE TITLE
Docs site down

### ISSUE THREAD

**Issue by nicbell** [TryKickoff/kickoff#123]
Sub pages on the docs site aren't showing.

**Comment by mrmartineau** [comment]
can you open a ticket in @trykickoff/trykickoff.github.io?

**Comment by mrmartineau** [comment]
BTW, I just setup siteleaf to manage the site, it appears to have done something weird..

**Comment by mrmartineau** [comment]
@nicbell site fixed now btw

**Comment by nicbell** [comment]
Looks good to me
