### ISSUE TITLE
Fix SVG minification

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#128]
SVG minification in the `next` branch is currently broken. I have seen a few issues, one of which seemed to remove actual items from the compressed code. This, of course, affects the new SVG icon sprite-sheet workflow. SVGO is probably to blame for this and I will investigate the various SVGO options to see if one of them is causing the error. It could also be due to strangely formatted SVG code itself.. watch this space 👀

**Comment by rentorm** [comment]
Do you have mode details on this issue and how could I reproduce it? 
Maybe you can share files which caused the issue and I could try to have a look.

**Comment by mrmartineau** [comment]
@rentorm I experienced a few issues where some svg paths or even groups were being removed. I have not been able to find the issue. I should find the offending SVG, the TMW logo, and add to the ticket..

**Comment by mrmartineau** [comment]
Turned out to be a malformed SVG source file..
