### ISSUE TITLE
Generated CSS file not respect the name given in config.js

### ISSUE THREAD

**Issue by RobDesideri** [TryKickoff/kickoff#157]
### Overview of the Issue
If you set the [config.css.distFile option](https://github.com/TryKickoff/kickoff/blob/master/.kickoff/config.js#L23), the builded css file keep the default 'kickoff.css' name.
### Motivation
Settings permit this options, but it isn't implemented.
### Kickoff Version
8.0.0
### Suggest a Fix
Insert in css.js task a simple pipeline operation renaming the kickoff file to the setted name:
```
const path = require('path');

// ...already present code...

    .pipe(tap( file => {
      if(path.basename(file.path) === 'kickoff.css') {
        file.path = path.join(path.dirname(file.path), config.css.distFile + '.css')
      }
    }))
```

**Comment by mrmartineau** [comment]
Thanks @RobDesideri, I have just merged your PR #159 👍
