### ISSUE TITLE
TryKickoff is currently using the "Contributor Covenant", which is currently incompatible with its current membership

### ISSUE THREAD

**Issue by DelanoJ84** [TryKickoff/kickoff#191]
I opened an issue on the Contributor Covenant repo observing that an active maintainer has promoted the use of violence to suppress journalists: https://github.com/ContributorCovenant/contributor_covenant/issues/393

I think we should give the Contributor Covenant team a chance to make their code of conduct compatible with their active maintainers before closing this issue and removing the CoC.

**Comment by ashleynolan** [comment]
We use the contributor covenant conduct to hold the maintainers of our project accountable to the standards we expect in terms of respecting diversity and inclusion.

By removing this code of conduct, all we would be doing would be damaging this aim.

Closing this issue as I don’t think it’s particularly relevant.
