### ISSUE TITLE
Styleguide updates and improvements

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#48]
As part of the next slew of updates, I want to improve the styleguide. As #47 mentions, it is currently a little confusing to use the styleguide, and maintain it, while working on a project. 

My tasks at the moment are:

- [x] Improve the styleguide’s design
- [ ] Use [Statix](http://tmwagency.github.io/kickoff/statix/) to manage the styleguide - this should make it easier to develop allowing devs to create all components as includes and have multiple pages if need be.
- [x] Styleguides should look like the site that you're developing but I would like some Kickoff branding somewhere on the page (probably a footer or something

I recently found [Heroku's styleguide](http://purple.herokuapp.com/), we could take some inspiration from that.. @ashleynolan do we want to have code snippets in ours as well?

**Comment by ashleynolan** [comment]
I like the idea of code snippets, but think they should only be included if it can be easily maintained.

Could be something we play around with with the next round of improvements though for sure.

**Comment by mrmartineau** [comment]
perhaps the styleguide resides in its own repo then is integrated into the generator. That means the base framework is much more simple...

**Comment by ashleynolan** [comment]
I do think there should be a styleguide in Kickoff’s base, as it is an important part of any project, and so remving it seems counter-intuitive for those not using the generator.

Maybe we need to just sketch out the workflow of this to work out how it best sits and can be maintained alongside the rest of the framework?

**Comment by mrmartineau** [comment]
Should it be based on Statix? I think it will make it much easier to maintain but will probably be harder for most users to use as its not a simple html file anymore.. Opinions? / @nicbell @munkychop

**Comment by mrmartineau** [comment]
More examples can be found at http://styleguides.io/examples.html

**Comment by ashleynolan** [comment]
I think it should be whatever we think is easier to get to grips with and maintain.

Maintenance is the number 1 issue with a style guide, above anything else.  I think it probably does make sense to use Statix, simply as it may then mean that there is much less overhead needed if it can be set up in the right way.
