### ISSUE TITLE
When recently installed kickoff try to load the wrong script

### ISSUE THREAD

**Issue by fabzl** [TryKickoff/kickoff#54]
when I installed kickoff for the first time .
it tried to load this script : 

assets/dist/js/script.js

when only this one was available: 
 assets/dist/js/script.min.js

**Comment by mrmartineau** [comment]
Hey @fabzl, are you saying that the `index.html` is wrong? Are you using the Yeoman generator?

**Comment by fabzl** [comment]
yes, as the index should load the minified version from dist . right ? ..

**Comment by mrmartineau** [comment]
yeah, but what does it do now?
