### ISSUE TITLE
custom build name problem

### ISSUE THREAD

**Issue by fabzl** [TryKickoff/kickoff#55]
When create a custom build, everything is fine apart from the config that is still called KO.

KM = custom name 
//initialise KM object
var KM = {};
KO.Config.init();

**Comment by mrmartineau** [comment]
Hey @fabzl, are you using the Yeoman generator?

**Comment by fabzl** [comment]
yeap this .. line is  called .. :   KO.Config.init(); an it should KM .. 
also I think the css file is called Kickoff in some places I cant remember exactly . tbh.

**Comment by mrmartineau** [comment]
Hi @fabzl, I have just pushed a fix for this in the [generator-kickoff](https://github.com/TryKickoff/generator-kickoff/commit/f9be19feac1e5dd03e772e0290945e7a281f9c55) repo

Thanks for raising the ticket.
