### ISSUE TITLE
Update latest version of normalize.css

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#56]
Normalize has been updated many times since we last updated it, so we should update it. I saw on the project [Github page](https://github.com/necolas/normalize.css) that it can be installed with npm, so I thought that we could ensure we always use the latest version if we add to `package.json` and then reference it in `_dependencies.scss`. This would be amazing but the lib would be in the `npm_modules` folder, which would make writing the path annoying so we may need to write a post npm install script to copy the file across..

Thoughts? 

/cc @ashleynolan @nicbell

**Comment by ashleynolan** [comment]
Agreed on the update – I’ve got no problems with it being installed as an NPM dependency either, think that’s definitely a good idea.

Not sure if you’d need to copy it over using a post script, as it’ll be clearer then that it’s a separate dependency if the path reflects this too?  I get that the path might be ugly, but if it never changes, then that shouldn’t matter really.

On a related note – I saw that Bootstrap are dropping normalise in favour of it’s own 'enhanced version' of the file, called [Reboot](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss).  Might be worth keeping an eye on and taking a look at when we get chance to see what it does add (I haven’t had chance to take a proper look at it yet, so can’t vouch for it actually being 'enhanced'!)

**Comment by mrmartineau** [comment]
That's interesting, they include `box-sizing` like we do: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L20-L28. It's not a separate npm module though :disappointed:

**Comment by ashleynolan** [comment]
Yeh, it’s only in Alpha atm – might become one when Bootstrap v4 gets released though.

**Comment by mrmartineau** [comment]
After mostly error and a bit of trial, @nicbell suggested manually doing this because Normalize doesn't get updated very often. Too much effort for such a small gain..
