### ISSUE TITLE
Next version of Kickoff

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#60]
Hey @ashleynolan & @nicbell, here's my list for the next version of Kickoff, please add any other things that you'd like. I don't think this is a v6, but probably a v5.1.0.. what do you think?

- [x] Switch to Browserify? see #57 
 - [x] Switch to minifify in the Browserify build
 - [x] Remove `grunt-contrib-uglify`
 - [x] Remove `chotto` if we move to Browserify build is not needed anymore
- [x] Add a modifier to `.l-blockGrid` > `.l-blockgrid--guttered`. Thanks @nicbell 
 - [x] remove dependency on unordered lists @nicbell, will you be able to do this?
- [x] Update custom radios & checkboxes. 50% done by @mrmartineau
- [x] Remove some grunt plugins
 - [x] Remove Grunt photobox, what do you think?
- [x] Update package.json to move some items in `optionalDependencies`. @nicbell 
- [x] Refactor the `.media` element so it doesn't **always** stack on skinny viewports
- [x] Simplify tables @ashleynolan #61 
- [x] Add jsHint and scsslint tasks @ashleynolan 
- [x] Use cutting the mustard test for loading shims

**Comment by ashleynolan** [comment]
I think all of those sound like sensible things to move towards.  I’ll have a think if there’s anything else that might be worth adding.

Happy to pickup the Browserify stuff  – I’m on holiday for a few weeks from next Thursday, but can do it when I get back (unless someone else wants to do it before then).

**Comment by mrmartineau** [comment]
We can handle the Browserify stuff. We (@nicbell & I) have a good setup on our current project so will port it over. We are using minifify instead of uglify btw.

**Comment by ashleynolan** [comment]
Will add back in the SCSS and JS linting tasks tomorrow as should have time to do so then

**Comment by mrmartineau** [comment]
@ashleynolan once you have made the linting changes, we should have a code freeze. Cool?
