### ISSUE TITLE
Shall we remove modernizr?

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#63]
Just as the title states? Shall we remove modernizr? I can't remember the last time I used it properly on a project. If you just need to do the `no-js/js` switch, there are better ways to do that. If people want it, they can add it themselves.. What do you think @munkychop @nicbell @ashleynolan @ciaranpark

**Comment by munkychop** [comment]
Totally agree with removing Modernizr, as it's not something needed on every project and is very easy for people to add in themselves, if necessary.

**Comment by nicbell** [comment]
+1 for removing it.

**Comment by ashleynolan** [comment]
Think it should be removed from core, but should be in the generator as a question.

I use it mostly for flexbox fallbacks more than anything else now.

**Comment by mrmartineau** [comment]
Ok, great. It will be removed. Cheers guys.
