### ISSUE TITLE
imagemin: grunticon

### ISSUE THREAD

**Issue by jcoeklick** [TryKickoff/kickoff#65]
When running the build task, this error persists:

Running "imagemin:grunticon" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

Removing 'newer:imagemin:grunticon' from the 'icons' task allows the build to proceed.

npm cache clean && npm install grunt-contrib-imagemin was attempted but does not solve the problem.

**Comment by jcoeklick** [comment]
Thank you for the quick and helpful response.

To anyone else - this is what worked:

cd node_modules/grunt-contrib-imagemin
npm install imagemin@4.0.0

**Comment by mrmartineau** [comment]
Thanks @jcoeklick. I think version 1.0.0 includes imagmin 4.0.0 as a dependency so if you update that it will update imagemin too. 

Also, you should checkout our Twitter feed for the latest Kickoff news: https://twitter.com/trykickoff
