### ISSUE TITLE
When selecting statix in Yeoman generator missing comma in Gruntfile

### ISSUE THREAD

**Issue by tommaton** [TryKickoff/kickoff#67]
In V6 of Kickoff when using the Kickoff generator and choosing to use Statix a comma is missing from the complie task in the Gruntfile after images. 
````
grunt.registerTask('compile', [
		/* 'checks', / uncomment this line if you want to run linting checks on your SCSS/JS as part of your build*/
		'browserify',
		'postscss',
		'images'
		'copy:statix',
		'assemble',
		'shimly',
		'copy:modernizr'
	]);
````

**Comment by mrmartineau** [comment]
Thanks @tommaton, it has been fixed in v1.0.1 of the generator. FYI, generator-related issues should probably go in it's repo.
