### ISSUE TITLE
Issue with grunt-icon/NPM, causing error

### ISSUE THREAD

**Issue by ashleynolan** [TryKickoff/kickoff#69]
Grunt-icon seems to be causing issues when I go to `npm install` from a new Kickoff (and Statix) build.

I’m running node v5.4.1 and npm v3.3.12 (see included screengrab).

<img width="696" alt="screen shot 2016-01-19 at 10 45 22" src="https://cloud.githubusercontent.com/assets/805184/12416509/cd5e9946-be99-11e5-83d4-2a71e6c8768e.png">

It seems from a bit of hunting around online that this is an [NPM issue itself](https://github.com/npm/npm/issues/10344) rather than with grunticon, as trying to install worker-farm separately also doesn’t work for me.  As this is a dependency for grunticon this is why the error appears.

Not sure how often this issue occurs but may be worth seeing if it affects anyone else as it’ll stop people from being able to run Kickoff.

**Comment by mrmartineau** [comment]
grunticon has now been removed as have all 'icon' related grunt tasks
