### ISSUE TITLE
KO FlexGrid

### ISSUE THREAD

**Issue by ashleynolan** [TryKickoff/kickoff#74]
Making a list of things we need to do to finish off the new KO Flex-Grid work:

- [x] Move `.no-flexbox` floats and other column specific properties onto `.g-col`
- [x] Remove `singleCol` breakpoint, as no longer needed
- [x] Add variable toggle for `.no-flexbox` support in older browsers
- [x] Add breakpoint based stacking classes to the grid
- [x] Take `default: 0 ` out of the breakpoints map and just call the `g-span` mixin with null value to create the base span classes
- [x] Check to see what is required to make guttering work when flexbox isn’t supported and implement
- [x] Test grid properly when `no-flexbox` is the default state (in older browsers)
- [x] Delete any now unused mixins from `_grid-helpers.scss`
- [x] Document and test all grid scenarios
- [x] Move documentation of the new Flex-Grid documented in the kickoff docs site (removing the old grid and block-grid docs)
- [x] Add new grid to generator with new question asking whether float support is required.

**Comment by ashleynolan** [comment]
Small update – I’ve implemented the new grid system as a branch on the JUST EAT Platform, as it should be a good test of it’s base functionality.

I’m currently testing this over the next couple of days and then should be able to get started on the docs and generator updates.

**Comment by ashleynolan** [comment]
I’ve now added and tested the grid on JE – not a conclusive test, but it works well in IE8/9/10/11, Firefox and Chrome, as well as mobile browsers.

Going to move on to working on the docs next week now – should be able to do them and setup a bunch of use cases that can be tested then as well.  I’m happy with where the functionality is atm though :+1:

**Comment by ashleynolan** [comment]
Have done much more conclusive testing now – the new flexbox grid is running in production on JE now, and has been tested on pretty much everything I can think of.

Am currently moving the docs and test cases out of Kickoff main repo and into the docs site.  Hoping to get this finished in the next couple of days.  The grid should be ready to update in the generator now too though as it’s not going to change now barring any small tweaks resulting from any bug fixes 🚀

**Comment by mrmartineau** [comment]
@ashleynolan that's awesome! Do you have a link for where its being used on JE?

Do you think we ought to make it its own repo?

**Comment by ashleynolan** [comment]
I was thinking about that, yeh.  Is there anyway we can automatically pull it back into kickoff if we do that (I’ve never used git modules so not sure if this would be a use case for them…).

It’s used in a few places on the homepage of the international sites ([so Canada for example](https://www.just-eat.ca/?opt=0a5674029)) as well as on all the account pages (although you need to login to see them!).  It will be on the search results and menu pages soon as well when I get chance to update them 👍

**Comment by mrmartineau** [comment]
Do you mean git submodules? If so I think they're quite a pain in the arse. I have looked into this sort of thing in the past because I wanted a better way to update the generator since most of the time the `scss` folder is copied straight to the generator. I created https://github.com/TryKickoff/scss for just this purpose, so it could be shared with the generator and the main repo and be installed via npm if need be.. If anyone reading this know how to achieve this, we would love some input. 🙏

**Comment by ashleynolan** [comment]
Yeh, that’s what I was thinking as well – never had chance to actually look into it properly but always is a pain having to update in multiple places.

**Comment by mrmartineau** [comment]
@ashleynolan what do you think the generator question should be? we currently ask if <=IE8 needs to be supported, should we ask is IE9 should be too?

**Comment by ashleynolan** [comment]
Generator for the flex-grid?  I guess "Would you like to provide fallback classes for non-flexbox supported browsers?"

Does that sound ok?

**Comment by mrmartineau** [comment]
That's good, but I though this might be better: 

> Provide Flexbox feature-detect? Needed if you use our grid in non-flexbox supporting browsers

**Comment by ashleynolan** [comment]
That's good too :)
